Responsive design final
Stephanie041996/week2Milestone1 pull request #9
Opened 2021-02-23 15:09 UTC by Stephanie041996

updated media queries
updated nav for mobile view
updated sections for mobile view

2021-02-23 20:27 UTC, steph199607 commented
good work

2021-02-23 22:05 UTC, LamiaSristy requested changes
# Status: Change Required. ♻️

Hello @Stephanie041996  and @Solenka1.
Very nicely done. This is the only beginning of learning, keep the spirit always up. 🙌 

## The highlights: 

* The git-flow is correct.💯
*  The linters configs are added correctly.💯
*  README is descriptive.👍
*  Nice work with live demo.👌

## What to do next:  ⏩ 
**You need to work some more to get approval for this project**
**Please check my required points below** 👇 
##
**[REQUIRED]**
- [ ] You need to create the website for the 3 screen sizes, see from [pathwright](https://microverse.pathwright.com/library/new-technical-curriculum/177956/path/step/104325432/). Currently the tablet size is not working
- [ ]  Start with the mobile version and create the media-queries for the tablet and desktop ones. `Tablet: min-width around 768px`, `Desktop: min-width 1024px`.
- [x]  There are a lot of repeated codes in your stylesheets. You can create a custom class for the same code block, like,  .flex {display: flex};
- [x] Create variables for the colors in the stylesheet. Read [here](https://www.w3schools.com/css/css3_variables.asp)
- [x] In your design the `search` icon in Nav3 is not showing, but I can see it in the index file.
- [x] Use the `header` tag for the header, it's the best practice.
- [x] The header sticks to the top of the screen when the user scrolls down. See from the [page](https://perma.cc/M5ZV-Q2D6)
- [x] In desktop design there is a red overlay with a gradient in the top half of the first article.
![pic111](https://user-images.githubusercontent.com/56501603/108913246-fde03c80-7629-11eb-8e78-7fbb52985284.png)
Add this gradient design to your project.
- [x] Use the `nav` tag for the `Footer` which contains social media icons centered.
- [ ] Add a section in your `README` file to add instructions on how to download and run your project locally. 

##

**Please make the changes and ask for a re-review.**

Feel free to reach me on slack @lamiasristy 🙋
Happy Coding 💻

2021-02-25 14:16 UTC, whiz25 requested changes
## Changes Required 🙏🏿 
Nice job making the required changes as suggested. Your page looks more like the given design.
Let's make the following changes before merging.
- [x] Add `.vscode` folder to `.gitignore` file.
- [x] Check my comments for some ways to properly format your readme file.


### Martin Afani

2021-02-25 14:16 UTC, whiz25 commented on README.md
> +###Steps by download
- Give it some space to properly format. `### Steps by download`. This sentence should be something like `### Steps to download`. It makes more sense grammatically.

2021-02-25 14:16 UTC, whiz25 commented on README.md
> +###steps By cloning
- Add space for proper formatting

2021-02-26 14:31 UTC, uryelah approved these changes
Hi **@Stephanie041996**, I'm Sarah your reviewer for this PR 👩‍🚀 

Good job improving your README file and adding `.vscode` to your `.gitignore`.

You should be good to go now. Good luck with the next project! 🚀  

-------

## **Your project is approved! 🎊 🥅 💛**

**You may close this Pull Request and merge the changes**

---
    
## **Optional Suggestions**

- [ ] [OPTIONAL] In order to make sure the `.vscode/` folder, committed by accident, is removed from your repository you first need to follow a couple of steps.

As you may have noticed already, simply including the unrelated folder in the `.gitignore` does not remove it from the repository.

_What you need to do to properly remove the folder is:_
1. Remove it from `.gitignore`
2. Delete the folder/files 
3. Add, commit, and push
4. Re-add it to the `.gitignore`

Then in the next commits you make the folder will not be pushed anymore to your GitHub repo 😀 

---
    
**Keep being an awesome dev and good luck with your next project!**

---------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2021-02-26 16:14 UTC, merged